version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 5000:5000

    environment:
      - DATABASE=mongodb://database:27017/monitoring
  database:
    image: mongo
    ports:
      - 27017:27017
